package com.javacode.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@Table(name = "feedback")
public class Feedback {
    /*
     * 主键
     * */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   //自增
    private Long id;

    /**
     *   创建时间
     */
    private String createtime;

    /**
     *   反馈标题
     */
    private String title;

    private String userphone;

    private Date replytime;

    private String replyname;

    private String replyphone;
    /**
     *   反馈内容
     */
    private String content;

    /**
     *   处理状态：0待处理 1已处理
     *   默认未处理
     */
    private Integer status = 0;

    /**
     *   回复内容
     */
    private String reply;

    /**
     *   联系人姓名
     */
    private String username;

    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public String getUserphone() {
        return userphone;
    }

    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    public Date getReplytime() {
        return replytime;
    }

    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    public String getReplyname() {
        return replyname;
    }

    public void setReplyname(String replyname) {
        this.replyname = replyname;
    }

    public String getReplyphone() {
        return replyphone;
    }

    public void setReplyphone(String replyphone) {
        this.replyphone = replyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.title
     *
     * @return the value of feedback.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.title
     *
     * @param title the value for feedback.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.content
     *
     * @return the value of feedback.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.content
     *
     * @param content the value for feedback.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.status
     *
     * @return the value of feedback.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.status
     *
     * @param status the value for feedback.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.reply
     *
     * @return the value of feedback.reply
     *
     * @mbg.generated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.reply
     *
     * @param reply the value for feedback.reply
     *
     * @mbg.generated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.username
     *
     * @return the value of feedback.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }


    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

}