package com.javacode.entity;

import javax.persistence.*;
import java.util.Date;

/**
 *服药
 */
@Table(name = "mediinfo")
public class Mediinfo {
    /*
     * 主键
     * */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   //自增
    private Long id;

    @Column(name = "phone")
    private String phone;

    @Column(name = "name")
    private String name;

    @Column(name = "medicine")
    private String medicine;

    @Column(name = "total")
    private Integer total;

    /**
     *服用方法
     */
    private String method;

    /**
     *药品余量
     */
    private Integer allowance;

    /**
     *服用天数
     */
    private Integer day;

    /**
     *服用日期
     */
    private String date;


    @Column(name = "datetime")
    private  String datetime;


    public String getDatetime() {
        return datetime;
    }

    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.id
     *
     * @return the value of mediinfo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediinfo.id
     *
     * @param id the value for mediinfo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.phone
     *
     * @return the value of mediinfo.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediinfo.phone
     *
     * @param phone the value for mediinfo.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.name
     *
     * @return the value of mediinfo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getMedicine() {
        return medicine;
    }

    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.total
     *
     * @return the value of mediinfo.total
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediinfo.total
     *
     * @param total the value for mediinfo.total
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.method
     *
     * @return the value of mediinfo.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediinfo.method
     *
     * @param method the value for mediinfo.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.allowance
     *
     * @return the value of mediinfo.allowance
     *
     * @mbg.generated
     */
    public Integer getAllowance() {
        return allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediinfo.allowance
     *
     * @param allowance the value for mediinfo.allowance
     *
     * @mbg.generated
     */
    public void setAllowance(Integer allowance) {
        this.allowance = allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.day
     *
     * @return the value of mediinfo.day
     *
     * @mbg.generated
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediinfo.day
     *
     * @param day the value for mediinfo.day
     *
     * @mbg.generated
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediinfo.date
     *
     * @return the value of mediinfo.date
     *
     * @mbg.generated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediinfo.date
     *
     * @param date the value for mediinfo.date
     *
     * @mbg.generated
     */
    public void setDate(String date) {
        this.date = date;
    }

}