package com.javacode.entity;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


@Table(name = "oldinfo")
public class Oldinfo {
    /*
     * 主键
     * */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)   //自增
    private Long id;

    private String name;
    private Integer eage;
    private Date birthdate;
    private String esex;
    private String estreet;
    private String eaddress;

    private String phone;

    private Double ehealth = 100.00;

    private String creattime;

    private Integer familyid;

    private String picture;
    private String mate;
    private String body;
    private String illnessid;
    private String smoke;
    private String drink;

    @Transient
    private String illness;

    /*
    老人图片具体地址列表,数据库中没有
     */
    @Transient
    private List<Long> fileList;

    /*
    老人家属姓名,数据表中是id，这里转换为姓名
     */
    @Transient
    private String familyname;


    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public Integer getFamilyid() {
        return familyid;
    }

    public void setFamilyid(Integer familyid) {
        this.familyid = familyid;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldinfo.name
     *
     * @return the value of oldinfo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldinfo.name
     *
     * @param name the value for oldinfo.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldinfo.eage
     *
     * @return the value of oldinfo.eage
     *
     * @mbg.generated
     */
    public Integer getEage() {
        return eage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldinfo.eage
     *
     * @param eage the value for oldinfo.eage
     *
     * @mbg.generated
     */
    public void setEage(Integer eage) {
        this.eage = eage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldinfo.esex
     *
     * @return the value of oldinfo.esex
     *
     * @mbg.generated
     */
    public String getEsex() {
        return esex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldinfo.esex
     *
     * @param esex the value for oldinfo.esex
     *
     * @mbg.generated
     */
    public void setEsex(String esex) {
        this.esex = esex == null ? null : esex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldinfo.estreet
     *
     * @return the value of oldinfo.estreet
     *
     * @mbg.generated
     */
    public String getEstreet() {
        return estreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldinfo.estreet
     *
     * @param estreet the value for oldinfo.estreet
     *
     * @mbg.generated
     */
    public void setEstreet(String estreet) {
        this.estreet = estreet == null ? null : estreet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldinfo.eaddress
     *
     * @return the value of oldinfo.eaddress
     *
     * @mbg.generated
     */
    public String getEaddress() {
        return eaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldinfo.eaddress
     *
     * @param eaddress the value for oldinfo.eaddress
     *
     * @mbg.generated
     */
    public void setEaddress(String eaddress) {
        this.eaddress = eaddress == null ? null : eaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oldinfo.phone
     *
     * @return the value of oldinfo.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oldinfo.phone
     *
     * @param phone the value for oldinfo.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public Double getEhealth() {
        return ehealth;
    }

    public void setEhealth(Double ehealth) {
        this.ehealth = ehealth;
    }

    public List<Long> getFileList() {
        return fileList;
    }

    public void setFileList(List<Long> fileList) {
        this.fileList = fileList;
    }

    public String getFamilyname() {
        return familyname;
    }

    public void setFamilyname(String familyname) {
        this.familyname = familyname;
    }

    public Date getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getCreattime() {
        return creattime;
    }

    public void setCreattime(String creattime) {
        this.creattime = creattime;
    }

    public String getMate() {
        return mate;
    }

    public void setMate(String mate) {
        this.mate = mate;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }


    public String getSmoke() {
        return smoke;
    }

    public void setSmoke(String smoke) {
        this.smoke = smoke;
    }

    public String getDrink() {
        return drink;
    }

    public void setDrink(String drink) {
        this.drink = drink;
    }

    public String getIllnessid() {
        return illnessid;
    }

    public void setIllnessid(String illnessid) {
        this.illnessid = illnessid;
    }

    public String getIllness() {
        return illness;
    }

    public void setIllness(String illness) {
        this.illness = illness;
    }

    //将illnessid提取为一个列表
    public List<Long> getIllnessIds() {
        List<Long> ids = new ArrayList<>();
        if (illnessid != null && !illnessid.isEmpty()) {
//            System.out.println("原始 illnessid 字段的值：" + illnessid);
            String[] idStrings = illnessid.substring(1, illnessid.length() - 1).split(",");
            for (String idString : idStrings) {
                String trimmedIdString = idString.trim();
//                System.out.println("处理前的 ID 字符串：" + trimmedIdString);
                // 过滤掉无效的 ID 字符串
                if (!trimmedIdString.isEmpty()) {
                    try {
                        long id = Long.parseLong(trimmedIdString);
                        ids.add(id);
                    } catch (NumberFormatException e) {
//                        System.err.println("无效的 ID 字符串：" + trimmedIdString);
                        // 可以选择跳过无效的 ID 或者记录错误信息
                        // e.printStackTrace(); // 如果需要打印完整的异常堆栈信息
                    }
                }
            }
        }
        return ids;
    }


}